zeebe.client.cloud.region=bru-2
zeebe.client.cloud.clusterId=0c598896-2747-407e-9172-3f8fad3ccfd3
zeebe.client.cloud.clientId=kF26zcHD1NeZh.VleB_ZY.gYOnCx9bCS
zeebe.client.cloud.clientSecret=BZ6htJ6v~F2jYU32JqmyO5MO79HE94C8d5mGKSl10h.ZeAa7pH5yhpXU_jpalNsl
ZEEBE_REST_ADDRESS=https://bru-2.zeebe.camunda.io/0c598896-2747-407e-9172-3f8fad3ccfd3
ZEEBE_GRPC_ADDRESS=grpcs://0c598896-2747-407e-9172-3f8fad3ccfd3.bru-2.zeebe.camunda.io:443
ZEEBE_TOKEN_AUDIENCE=zeebe.camunda.io
