zeebe.client.cloud.region=bru-2
zeebe.client.cloud.clusterId=accd22b6-cc88-4b5e-aa4a-aaeab7b3e350
zeebe.client.cloud.clientId=PfJmZ~4wTdw_bqAQXGMIqZsVQ.I1gASI
zeebe.client.cloud.clientSecret=CMUgEQK_o.~yHpdxTkskSOJ0walZIkuAAinjb5KKJhyo9sxdLVlNzd4sB8iwhNGG
ZEEBE_REST_ADDRESS=https://bru-2.zeebe.camunda.io/accd22b6-cc88-4b5e-aa4a-aaeab7b3e350
ZEEBE_GRPC_ADDRESS=grpcs://accd22b6-cc88-4b5e-aa4a-aaeab7b3e350.bru-2.zeebe.camunda.io:443
ZEEBE_TOKEN_AUDIENCE=zeebe.camunda.io
